config/routes.rb
Rails.application.routes.draw do
  resources :job_templates, :except => [:show] do
    member do
      get 'clone_template'
      get 'lock'
      get 'export'
      get 'unlock'
      post 'preview'
    end
    collection do
      post 'preview'
      post 'import'
      get 'revision'
      get 'auto_complete_search'
      get 'auto_complete_job_category'
    end
  end

  match 'job_invocations/new', to: 'react#index', :via => [:get], as: 'new_job_invocation'
  match 'job_invocations/new', to: 'job_invocations#create', via: [:post], as: 'create_job_invocation'
  match 'job_invocations/', to: 'job_invocations#legacy_create', via: [:post], as: 'legacy_create_job_invocation'
  match 'job_invocations/:id/rerun', to: 'react#index', :via => [:get], as: 'rerun_job_invocation'
  match 'old/job_invocations/new', to: 'job_invocations#new', via: [:get], as: 'form_new_job_invocation'
  match 'old/job_invocations/:id/rerun', to: 'job_invocations#rerun', via: [:get, :post], as: 'form_rerun_job_invocation'
  get 'legacy/job_invocations/:id', to: 'job_invocations#show', as: 'legacy_job_invocation'
  match 'job_invocations_detail/:id/host_invocation/:host_id', to: 'react#index', :via => [:get], as: 'new_job_invocation_detail_by_host'
  get 'show_template_invocation_by_host/:host_id/job_invocation/:id', to: 'template_invocations#show_template_invocation_by_host'

  resources :job_invocations, :only => [:create, :index] do
    collection do
      get 'preview_job_invocations_per_host'
      post 'refresh'
      get 'chart'
      get 'preview_hosts'
      get 'auto_complete_search'
    end
    member do
      get 'hosts', to: 'job_invocations#list_jobs_hosts'
      post 'cancel'
    end
  end

  get 'job_invocations/:id', to: 'react#index', as: 'job_invocation'

  resources :remote_execution_features, :only => [:show, :index, :update]

  # index is needed so the auto_complete_search can be constructed, otherwise autocompletion in filter does not work
  resources :template_invocations, :only => [:show, :index] do
    collection do
      get 'auto_complete_search'
    end
  end

  constraints(:id => %r{[^/]+}) do
    get 'cockpit/host_ssh_params/:id', to: 'cockpit#host_ssh_params'
  end
  get 'cockpit/redirect', to: 'cockpit#redirect'
  get 'ui_job_wizard/categories', to: 'ui_job_wizard#categories'
  get 'ui_job_wizard/template/:id', to: 'ui_job_wizard#template'
  get 'ui_job_wizard/resources', to: 'ui_job_wizard#resources'
  get 'ui_job_wizard/job_invocation', to: 'ui_job_wizard#job_invocation'

  namespace :api, :defaults => {:format => 'json'} do
    scope '(:apiv)', :module => :v2, :defaults => {:apiv => 'v2'}, :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      resources :job_invocations, :except => [:new, :edit, :update, :destroy] do
        resources :hosts, :only => :none do
          get '/', :to => 'job_invocations#output'
          get '/raw', :to => 'job_invocations#raw_output'
        end
        member do
          get 'hosts'
          post 'cancel'
          post 'rerun'
          get  'template_invocations', :to => 'template_invocations#template_invocations'
          get 'outputs'
          post 'outputs'
        end
      end

      resources :job_templates, :except => [:new, :edit] do
        resources :locations, :only => [:index, :show]
        resources :organizations, :only => [:index, :show]
        get :export, :on => :member
        post :clone, :on => :member
        collection do
          get 'revision'
          post 'import'
        end
      end

      resources :organizations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :locations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :templates, :only => :none do
        resources :foreign_input_sets, :only => [:index, :show, :create, :destroy, :update]
      end

      get 'hosts/:id/available_remote_execution_features', to: 'remote_execution_features#available_remote_execution_features'

      resources :remote_execution_features, :only => [:show, :index, :update]
    end
  end
end

app/models/template_invocation.rb
class TemplateInvocation < ApplicationRecord
  include Authorizable
  include ForemanTasks::Concerns::ActionSubject

  include ForemanRemoteExecution::ErrorsFlattener
  FLATTENED_ERRORS_MAPPING = { :input_values => lambda do |input_value|
                                                 _('Input') + " #{input_value.template_input.name}"
                                                end }.freeze


  belongs_to :template, :class_name => 'JobTemplate', :foreign_key => 'template_id'
  belongs_to :job_invocation, :inverse_of => :template_invocations
  has_many :input_values, :class_name => 'TemplateInvocationInputValue', :dependent => :destroy
  has_many :provider_input_values, :class_name => 'InvocationProviderInputValue', :dependent => :destroy
  has_one :targeting, :through => :job_invocation
  belongs_to :host, :class_name => 'Host::Managed', :foreign_key => :host_id
  has_one :host_group, :through => :host, :source => :hostgroup
  belongs_to :run_host_job_task, :class_name => 'ForemanTasks::Task'
  has_many :remote_execution_features, :through => :template
  has_many :template_invocation_events, :dependent => :destroy
  belongs_to :smart_proxy, :class_name => '::SmartProxy', :inverse_of => :template_invocations

  validates_associated :input_values
  validate :provides_required_input_values
  before_validation :set_effective_user

  scoped_search :relation => :host, :on => :name, :rename => 'host.name', :complete_value => true
  scoped_search :relation => :host_group, :on => :name, :rename => 'host_group.name', :complete_value => true
  scoped_search :relation => :template, :on => :job_category, :complete_value => true
  scoped_search :relation => :template, :on => :name, :complete_value => true
  scoped_search :relation => :remote_execution_features, :on => :name, :rename => 'feature'

  class TaskResultMap
    MAP = {
      :cancelled => :cancelled,
      :error     => :failed,
      :pending   => :pending,
      :running   => :pending,
      :success   => :success,
      :warning   => :failed,
    }.with_indifferent_access

    REVERSE_MAP = MAP.each_with_object({}) do |(key, value), acc|
      acc[value] ||= []
      acc[value] << key
    end.with_indifferent_access

    class << self
      def results
        MAP.keys.map(&:to_sym)
      end

      def statuses
        REVERSE_MAP.keys.map(&:to_sym)
      end

      # 1:1
      # error => failed
      def task_result_to_status(result)
        MAP[result].try(:to_sym) || result
      end

      # 1:n
      # failed => [:error, :warning]
      def status_to_task_result(status)
        if REVERSE_MAP.key? status
          REVERSE_MAP[status].map(&:to_sym)
        else
          Array(status)
        end
      end
    end
  end

  def template
    JobTemplate.unscoped { super }
  end

  def to_action_input
    { :id => id, :name => template.name }
  end

  def deep_clone
    self.dup.tap do |invocation|
      invocation.input_values = self.input_values.map(&:dup)
      invocation.provider_input_values = self.provider_input_values.map(&:dup)
    end
  end

  def deep_clone!
    deep_clone.tap(&:save!)
  end

  private

  def provides_required_input_values
    required_inputs = self.template.template_inputs.where(:required => true)
    missing_inputs = required_inputs.reject { |input| self.input_values.map(&:template_input_id).include?(input.id) }
    unless missing_inputs.empty?
      errors.add(:base, _('Not all required inputs have values. Missing inputs: %s') % missing_inputs.map(&:name).join(', '))
    end
  end

  def set_effective_user
    if template.provider.supports_effective_user?
      self.effective_user = Setting[:remote_execution_effective_user] if self.effective_user.blank?
    else
      self.effective_user = nil
    end
  end
end

app/controllers/api/v2/template_invocations_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class TemplateInvocationsController < ::Api::V2::BaseController

      before_action :find_job_invocation, :only => %w{template_invocations}

      api :GET, '/job_invocations/:job_invocation_id/template_invocations',
        N_('List template invocations belonging to job invocation')
      param_group :search_and_pagination, ::Api::V2::BaseController
      param :job_invocation_id, :identifier, :required => true
      def template_invocations
        @template_invocations = resource_scope.paginate(paginate_options)
        render :layout => 'api/v2/layouts/index_layout'
      end

      def resource_scope
        if params[:action] == 'template_invocations'
          resource_scope_for_template_invocations
        else
          super
        end
      end

      private

      def resource_scope_for_template_invocations
        @job_invocation.template_invocations
                       .includes(:host)
                       .where(host: Host.authorized(:view_hosts, Host))
                       .search_for(*search_options)
      end

      def find_job_invocation
        @job_invocation = JobInvocation.find(params[:id])
      end

      def action_permission
        case params[:action]
        when 'template_invocations'
          :view
        else
          super
        end
      end
    end
  end
end

app/controllers/template_invocations_controller.rb
class TemplateInvocationsController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include RemoteExecutionHelper
  include JobInvocationsHelper

  before_action :find_job_invocation, :only => %w{show_template_invocation_by_host}
  before_action :find_host, :only => %w{show_template_invocation_by_host}

  def controller_permission
    'job_invocations'
  end

  def show
    @template_invocation = TemplateInvocation.find(params[:id])
    raise ActiveRecord::RecordNotFound unless User.current.can?(:view_job_invocations, @template_invocation.job_invocation)

    @template_invocation_task = @template_invocation.run_host_job_task
    @host = @template_invocation.host
    @auto_refresh = @template_invocation_task.pending?
    @since = params[:since].to_f if params[:since].present?
    @line_sets = @template_invocation_task.main_action.live_output
    @line_sets = @line_sets.drop_while { |o| o['timestamp'].to_f <= @since } if @since
    @line_counter = params[:line_counter].to_i
  end

  def show_template_invocation_by_host
    @template_invocation = @job_invocation.template_invocations.find { |template_inv| template_inv.host_id == @host.id }
    if @template_invocation.nil?
      render :json => { :error => _('Template invocation not found') }, :status => :not_found
    end
    @template_invocation_task = @template_invocation.run_host_job_task

    lines = normalize_line_sets(@template_invocation_task.main_action.live_output)
    transformed_input_values = @template_invocation.input_values.joins(:template_input).map do |input_value|
      {
        name: input_value&.template_input&.name,
        value: input_safe_value(input_value),
      }
    end

    smart_proxy = @template_invocation.smart_proxy
    if smart_proxy
      proxy = {
        name: smart_proxy.name,
        href: smart_proxy_path(smart_proxy),
      }
    end

    auto_refresh = @job_invocation.task.try(:pending?)
    finished = @job_invocation.status_label == 'failed' || @job_invocation.status_label == 'succeeded' || @job_invocation.status_label == 'cancelled'
    render :json => { :output => lines, :preview => template_invocation_preview(@template_invocation, @host), :proxy => proxy, :input_values => transformed_input_values, :job_invocation_description => @job_invocation.description, :task => @template_invocation_task.attributes.merge({cancellable: @template_invocation_task.cancellable? }), :host_name => @host.name, :permissions => {
      :view_foreman_tasks => User.current.allowed_to?(:view_foreman_tasks),
      :cancel_job_invocations => User.current.allowed_to?(:cancel_job_invocations),
      :execute_jobs => User.current.allowed_to?(:create_job_invocations) && (!@host.infrastructure_host? || User.current.can?(:execute_jobs_on_infrastructure_hosts)),

    },
    :auto_refresh => auto_refresh, :finished => finished}, status: :ok
  end

  private

  def find_job_invocation
    @job_invocation = JobInvocation.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :json => { :error => { :message => format(_("Job with id '%{id}' was not found"), :id => params['id']) } }, :status => :not_found
  end

  def find_host
    @host = Host.find(params[:host_id])
  rescue ActiveRecord::RecordNotFound
    render :json => { :error => { :message => format(_("Host with id '%{id}' was not found"), :id => params['host_id']) } }, :status => :not_found
  end

  def template_invocation_preview(template_invocation, host)
    renderer = InputTemplateRenderer.new(template_invocation.template, host, template_invocation)
    output = load_template_from_task(template_invocation, host) || renderer.preview
    if output
      {:plain => output}
    else
      {status: :bad_request,
        plain: renderer.error_message }
    end
  end

end

app/views/template_invocations/_output_line_set.html.erb
<% output_line_set['output'].gsub("\r\n", "\n").sub(/\n\Z/, '').split("\n", -1).each do |line| %>
  <%= content_tag :div, :class => 'line ' + output_line_set['output_type'], :data => { :timestamp => output_line_set['timestamp'] } do %>

    <%= content_tag(:span, (@line_counter += 1).to_s.rjust(4).gsub(' ', '&nbsp;').html_safe + ':', :class => 'counter', :title => (output_line_set['timestamp'] && Time.at(output_line_set['timestamp'].to_f))) %>
    <%= content_tag(:div, colorize_line(line.gsub(JobInvocationOutputHelper::COLOR_PATTERN, '').empty? ? "#{line}\n" : line).html_safe, :class => 'content') %>
  <% end %>
<% end %>

app/views/template_invocations/_refresh.js.erb
<% if @auto_refresh %>
   if(window.allJsLoaded){
    delayed_refresh($("div.terminal").data('refresh-url'),
          {"since": "<%= @line_sets.last.try(:[], 'timestamp') || @since %>", "line_counter": $("div.terminal div.line").length})
  }
  else {
    $(document).on('loadJS', function() {
      delayed_refresh($("div.terminal").data('refresh-url'),
          {"since": "<%= @line_sets.last.try(:[], 'timestamp') || @since %>", "line_counter": $("div.terminal div.line").length})
    });
  }
<% end %>

app/views/template_invocations/show.html.erb
<% items = [{ :caption => _('Job invocations'), :url => job_invocations_path },
            { :caption => @template_invocation.job_invocation.description,
              :url => job_invocation_path(@template_invocation.job_invocation_id) }]

if @host
  items << { :caption => _('Template Invocation for %s') % @host }
  breadcrumbs(:resource_url => template_invocations_api_job_invocation_path(@template_invocation.job_invocation_id),
               :name_field => 'host_name',
               :switcher_item_url => template_invocation_path(':id'),
               :items => items)
else
  breadcrumbs(items: items, switchable: false)
end
%>

<% stylesheet 'foreman_remote_execution/foreman_remote_execution' %>
<% javascript 'foreman_remote_execution/template_invocation' %>

<div id="title_action">
  <div class="btn-toolbar pull-right">
    <%= button_group(link_to(_('Back to Job'), job_invocation_path(@template_invocation.job_invocation), :class => 'btn btn-default'),
                    (link_to(_('Rerun'), rerun_job_invocation_path(@template_invocation.job_invocation, :host_ids => [ @host.id ]), :class => 'btn btn-default') if authorized_for(:permission => :create_job_invocations))) %>
    <%= button_group(link_to_function(_('Toggle command'), '$("div.preview").toggle()', :class => 'btn btn-default'),
                     link_to_function(_('Toggle STDERR'), '$("div.line.stderr").toggle()', :class => 'btn btn-default'),
                     link_to_function(_('Toggle STDOUT'), '$("div.line.stdout").toggle()', :class => 'btn btn-default'),
                     link_to_function(_('Toggle DEBUG'), '$("div.line.debug").toggle()', :class => 'btn btn-default')) if @host %>
    <%= button_group(template_invocation_task_buttons(@template_invocation_task, @template_invocation.job_invocation)) %>
  </div>
</div>
<% if @host %>
  <% proxy = @template_invocation.smart_proxy %>
  <h3>
    <%= _('Target: ') %><%= link_to(@host, current_host_details_path(@host)) %>
    <% if proxy %>
      <%= _('using Smart Proxy') %> <%= link_to(proxy.name, smart_proxy_path(proxy)) %>
    <% end %>
  </h3>

  <div class="preview hidden">
    <%= preview_box(@template_invocation, @host) %>
  </div>

  <div class="terminal" data-refresh-url="<%= template_invocation_path(@template_invocation) %>">
    <% if @error %>
      <div class="line error"><%= @error %></div>
    <% else %>
      <%= link_to_function(_('Scroll to bottom'), '$("#rails-app-content").scrollTop($("#rails-app-content").prop("scrollHeight"));', :class => 'pull-right scroll-link-bottom') %>

      <div class="printable">
        <%= render :partial => 'output_line_set', :collection => normalize_line_sets(@line_sets) %>
      </div>

      <%= link_to_function(_('Scroll to top'), '$("#rails-app-content").scrollTop(0);', :class => 'pull-right scroll-link-top') %>
    <% end %>
  </div>

  <script>
    <%= render partial: 'refresh', formats: :js %>
  </script>
<% else %>
  <%= _("Could not display data for job invocation.") %>
<% end %>

app/views/template_invocations/show.js.erb
var scrolledToBottom = ($(window).scrollTop() + $(window).height() == $(document).height());

var lines = '<%=j render :partial => 'output_line_set', :collection => @line_sets %>';
var target = $("div.terminal div.printable");

<% if @since %>
  target.append(lines);
<% else %>
  target.html(lines);
<% end %>

<%= render partial: 'refresh', formats: :js %>

if (scrolledToBottom) {
  $("html, body").animate({ scrollTop: $(document).height() }, "slow");
}