config/routes.rb
Rails.application.routes.draw do
  resources :job_templates, :except => [:show] do
    member do
      get 'clone_template'
      get 'lock'
      get 'export'
      get 'unlock'
      post 'preview'
    end
    collection do
      post 'preview'
      post 'import'
      get 'revision'
      get 'auto_complete_search'
      get 'auto_complete_job_category'
    end
  end

  match 'job_invocations/new', to: 'react#index', :via => [:get], as: 'new_job_invocation'
  match 'job_invocations/new', to: 'job_invocations#create', via: [:post], as: 'create_job_invocation'
  match 'job_invocations/', to: 'job_invocations#legacy_create', via: [:post], as: 'legacy_create_job_invocation'
  match 'job_invocations/:id/rerun', to: 'react#index', :via => [:get], as: 'rerun_job_invocation'
  match 'old/job_invocations/new', to: 'job_invocations#new', via: [:get], as: 'form_new_job_invocation'
  match 'old/job_invocations/:id/rerun', to: 'job_invocations#rerun', via: [:get, :post], as: 'form_rerun_job_invocation'
  get 'legacy/job_invocations/:id', to: 'job_invocations#show', as: 'legacy_job_invocation'
  match 'job_invocations_detail/:id/host_invocation/:host_id', to: 'react#index', :via => [:get], as: 'new_job_invocation_detail_by_host'
  get 'show_template_invocation_by_host/:host_id/job_invocation/:id', to: 'template_invocations#show_template_invocation_by_host'

  resources :job_invocations, :only => [:create, :index] do
    collection do
      get 'preview_job_invocations_per_host'
      post 'refresh'
      get 'chart'
      get 'preview_hosts'
      get 'auto_complete_search'
    end
    member do
      get 'hosts', to: 'job_invocations#list_jobs_hosts'
      post 'cancel'
    end
  end

  get 'job_invocations/:id', to: 'react#index', as: 'job_invocation'

  resources :remote_execution_features, :only => [:show, :index, :update]

  # index is needed so the auto_complete_search can be constructed, otherwise autocompletion in filter does not work
  resources :template_invocations, :only => [:show, :index] do
    collection do
      get 'auto_complete_search'
    end
  end

  constraints(:id => %r{[^/]+}) do
    get 'cockpit/host_ssh_params/:id', to: 'cockpit#host_ssh_params'
  end
  get 'cockpit/redirect', to: 'cockpit#redirect'
  get 'ui_job_wizard/categories', to: 'ui_job_wizard#categories'
  get 'ui_job_wizard/template/:id', to: 'ui_job_wizard#template'
  get 'ui_job_wizard/resources', to: 'ui_job_wizard#resources'
  get 'ui_job_wizard/job_invocation', to: 'ui_job_wizard#job_invocation'

  namespace :api, :defaults => {:format => 'json'} do
    scope '(:apiv)', :module => :v2, :defaults => {:apiv => 'v2'}, :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      resources :job_invocations, :except => [:new, :edit, :update, :destroy] do
        resources :hosts, :only => :none do
          get '/', :to => 'job_invocations#output'
          get '/raw', :to => 'job_invocations#raw_output'
        end
        member do
          get 'hosts'
          post 'cancel'
          post 'rerun'
          get  'template_invocations', :to => 'template_invocations#template_invocations'
          get 'outputs'
          post 'outputs'
        end
      end

      resources :job_templates, :except => [:new, :edit] do
        resources :locations, :only => [:index, :show]
        resources :organizations, :only => [:index, :show]
        get :export, :on => :member
        post :clone, :on => :member
        collection do
          get 'revision'
          post 'import'
        end
      end

      resources :organizations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :locations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :templates, :only => :none do
        resources :foreign_input_sets, :only => [:index, :show, :create, :destroy, :update]
      end

      get 'hosts/:id/available_remote_execution_features', to: 'remote_execution_features#available_remote_execution_features'

      resources :remote_execution_features, :only => [:show, :index, :update]
    end
  end
end

app/controllers/api/v2/job_invocations_controller.rb
module Api
  module V2
    class JobInvocationsController < ::Api::V2::BaseController
      include ::Api::Version2
      include ::Foreman::Renderer
      include RemoteExecutionHelper

      before_action :find_optional_nested_object, :only => %w{output raw_output}
      before_action :find_host, :only => %w{output raw_output}
      before_action :find_resource, :only => %w{show update destroy clone cancel rerun outputs hosts}

      wrap_parameters JobInvocation, :include => (JobInvocation.attribute_names + [:ssh])

      api :GET, '/job_invocations/', N_('List job invocations')
      param_group :search_and_pagination, ::Api::V2::BaseController
      def index
        @job_invocations = resource_scope_for_index
      end

      api :GET, '/job_invocations/:id', N_('Show job invocation')
      param :id, :identifier, :required => true
      param :host_status, :bool, required: false, desc: N_('Show Job status for the hosts')
      def show
        set_hosts_and_template_invocations
        @job_organization = Taxonomy.find_by(id: @job_invocation.task.input[:current_organization_id])
        @job_location = Taxonomy.find_by(id: @job_invocation.task.input[:current_location_id])
        if params[:host_status] == 'true'
          set_statuses_and_smart_proxies
        end
      end

      def_param_group :job_invocation do
        param :job_invocation, Hash, :required => true, :action_aware => true do
          param :job_template_id, String, :required => false, :desc => N_('The job template to use, parameter is required unless feature was specified')
          param :targeting_type, String, :required => true, :desc => N_('Invocation type, one of %s') % Targeting::TYPES
          param :randomized_ordering, :bool, :desc => N_('Execute the jobs on hosts in randomized order')
          param :inputs, Hash, :required => false, :desc => N_('Inputs to use')
          param :ssh, Hash, :desc => N_('SSH provider specific options') do
            param :effective_user, String,
              :required => false,
              :desc => N_('What user should be used to run the script (using sudo-like mechanisms). Defaults to a template parameter or global setting.')
            param :effective_user_password, String,
              :required => false,
              :desc => N_('Set password for effective user (using sudo-like mechanisms)')
          end
          param :ssh_user, String, :required => false, :desc => N_('Set SSH user')
          param :password, String, :required => false, :desc => N_('Set SSH password')
          param :key_passphrase, String, :required => false, :desc => N_('Set SSH key passphrase')

          param :recurrence, Hash, :desc => N_('Create a recurring job') do
            param :cron_line, String, :required => false, :desc => N_('How often the job should occur, in the cron format')
            param :max_iteration, :number, :required => false, :desc => N_('Repeat a maximum of N times')
            param :end_time, DateTime, :required => false, :desc => N_('Perform no more executions after this time')
            param :purpose, String, :required => false, :desc => N_('Designation of a special purpose')
          end

          param :scheduling, Hash, :desc => N_('Schedule the job to start at a later time') do
            param :start_at, DateTime, :required => false, :desc => N_('Schedule the job for a future time')
            param :start_before, DateTime, :required => false, :desc => N_('Indicates that the action should be cancelled if it cannot be started before this time.')
          end

          param :concurrency_control, Hash, :desc => N_('Control concurrency level and distribution over time') do
            param :concurrency_level, Integer, :desc => N_('Run at most N tasks at a time')
          end

          param :bookmark_id, Integer, :required => false
          param :search_query, String, :required => false
          param :description_format, String, :required => false, :desc => N_('Override the description format from the template for this invocation only')
          param :execution_timeout_interval, Integer, :required => false, :desc => N_('Override the timeout interval from the template for this invocation only')
          param :feature, String, :required => false, :desc => N_('Remote execution feature label that should be triggered, job template assigned to this feature will be used')
          param :time_to_pickup, Integer, :required => false, :desc => N_('Override the global time to pickup interval for this invocation only')

          RemoteExecutionProvider.providers.each_value do |provider|
            next if !provider.respond_to?(:provider_inputs_doc) || provider.provider_inputs_doc.empty?
            doc = provider.provider_inputs_doc
            param doc[:namespace], Hash, doc[:opts] do
              doc[:children].map do |input|
                param input[:name], input[:type], input[:opts]
              end
            end
          end
        end
      end

      api :POST, '/job_invocations/', N_('Create a job invocation')
      param_group :job_invocation, :as => :create
      def create
        composer = JobInvocationComposer.from_api_params(
          job_invocation_params
        )
        composer.trigger!
        @job_invocation = composer.job_invocation
        @hosts = @job_invocation.targeting.hosts
        process_response @job_invocation
      rescue JobInvocationComposer::JobTemplateNotFound, JobInvocationComposer::FeatureNotFound => e
        not_found(error: { message: e.message })
      end

      api :GET, '/job_invocations/:id/hosts/:host_id', N_('Get output for a host')
      param :id, :identifier, :required => true
      param :host_id, :identifier, :required => true
      param :since, String, :required => false
      def output
        if @nested_obj.task.scheduled?
          render :json => delayed_task_output(@nested_obj.task, :default => [])
          return
        end

        render :json => host_output(@nested_obj, @host, :default => [], :since => params[:since])
      end

      api :GET, '/job_invocations/:id/hosts', N_('List hosts belonging to job invocation')
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(JobInvocation)
      param :id, :identifier, :required => true
      def hosts
        set_hosts_and_template_invocations
        set_statuses_and_smart_proxies
        @total = @hosts.size
        @hosts = @hosts.search_for(params[:search], :order => params[:order]).paginate(:page => params[:page], :per_page => params[:per_page])
        @subtotal = @hosts.total_entries
        if params[:awaiting]
          @hosts = @hosts.select { |host| @host_statuses[host.id] == 'N/A' }
        end
        render :hosts, :layout => 'api/v2/layouts/index_layout'
      end

      api :GET, '/job_invocations/:id/hosts/:host_id/raw', N_('Get raw output for a host')
      param :id, :identifier, :required => true
      param :host_id, :identifier, :required => true
      def raw_output
        if @nested_obj.task.scheduled?
          render :json => delayed_task_output(@nested_obj.task)
          return
        end

        render :json => host_output(@nested_obj, @host, :raw => true)
      end

      api :POST, '/job_invocations/:id/cancel', N_('Cancel job invocation or matching tasks only')
      param :id, :identifier, :required => true
      param :force, :bool
      param :search, String, :desc => N_('Search query to cancel tasks only on matching hosts. If not provided, the whole job invocation will be cancelled.')
      def cancel
        force = params.fetch('force', false)
        search = params[:search]

        if search.present?
          begin
            hosts_scope = @job_invocation.targeting.hosts.authorized(:view_hosts, Host)
            matching_hosts = hosts_scope.search_for(search)
            tasks_to_process = @job_invocation.template_invocations
                                              .where(host_id: matching_hosts.select(:id))
                                              .includes(:run_host_job_task)

            cancelled, skipped = tasks_to_process.partition { |ti| ti.run_host_job_task&.cancellable? }
            cancelled.each do |ti|
              if force
                ti.run_host_job_task.abort
              else
                ti.run_host_job_task.cancel
              end
            end
            render json: {
              total: tasks_to_process.size,
              cancelled: cancelled.map(&:run_host_job_task_id),
              skipped: skipped.map(&:run_host_job_task_id),
            }
          rescue StandardError => e
            render json: { error: { message: "Failed to cancel tasks on hosts: #{e.message}" } }, status: :unprocessable_entity
          end
        elsif @job_invocation.task.cancellable?
          result = @job_invocation.cancel(force)
          render json: { cancelled: result, id: @job_invocation.id }
        else
          render json: { message: _('The job could not be cancelled.') }, status: :unprocessable_entity
        end
      end

      api :POST, '/job_invocations/:id/rerun', N_('Rerun job on failed hosts')
      param :id, :identifier, :required => true
      param :failed_only, :bool
      param :succeeded_only, :bool
      def rerun
        composer = JobInvocationComposer.from_job_invocation(@job_invocation, params)
        if composer.rerun_possible?
          composer.trigger!
          @job_invocation = composer.job_invocation
          process_response @job_invocation
        else
          render :json => { :error => _('Could not rerun job %{id} because its template could not be found') % { :id => composer.reruns } },
            :status => :not_found
        end
      end

      api :GET, '/job_invocations/:id/outputs', N_('Get outputs of hosts in a job')
      param :id, :identifier, :required => true
      param :search_query, :identifier, :required => false

app/helpers/job_invocations_helper.rb
# frozen_string_literal:true

module JobInvocationsHelper
  def minicard(icon, number, text, tooltip: nil)
    tooltip_options = tooltip ? { :'data-original-title' => tooltip, :rel => 'twipsy' } : {}
    content_tag(:div, :class => 'card-pf card-pf-accented
                card-pf-aggregate-status card-pf-aggregate-status-mini') do
      content_tag(:h2, { :class => 'card-pf-title', :style => 'line-height: 1.1' }.merge(tooltip_options)) do
        icon_text(icon, '', :kind => 'pficon') +
        content_tag(:span, number, :class =>'card-pf-aggregate-status-count') +
        text
      end
    end
  end

  def template_name_and_provider_link(template)
    template_name = content_tag(:strong, template.name)
    provider = template.provider.humanized_name
    link_content = template_name + ' - ' + provider + ' ' +
      icon_text('edit', '', :kind => 'pficon')
    link_to_if_authorized(link_content,
      hash_for_edit_job_template_path(:id => template.id))
  end

  def preview_hosts(template_invocation)
    hosts = template_invocation.targeting.hosts.authorized(:view_hosts, Host).take(20)
    hosts.map do |host|
      collapsed_preview(host) +
        render(:partial => 'job_invocations/user_input',
          :locals => { :template_invocation => template_invocation,
                       :target => host })
    end.reduce(:+)
  end

  def collapsed_preview(target)
    title = (target || 'N/A').to_s
    content_tag(:h5,
      :class => "expander collapsed out",
      :data => { :toggle => 'collapse',
                 :target => "#preview_#{target.id}" }) do
      content_tag(:span, '', :class => 'caret') + title
    end
  end

  def show_job_organization(organization)
    organization.presence || _('Any Organization')
  end

  def show_job_location(location)
    location.presence || _('Any Location')
  end

  def input_safe_value(input)
    template_input = input.template_input
    template_input.respond_to?(:hidden_value) && template_input.hidden_value ? '*' * 5 : input.value
  end
end

app/views/job_invocations/_card_results.html.erb
<div id="job-invocation-chart">
  <div class="card-pf card-pf-accented card-pf-aggregate-status">
    <h2 style="height: 18px;" class="card-pf-title">
      <a href="#"><%= _('Results') %></a>
    </h2>
    <div class="card-pf-body">
      <div id='status_chart'>
        <%= react_component('JobInvocationContainer', data: { url: "/job_invocations/chart?id=#{job_invocation.id}" }) %>
      </div>
    </div>
  </div>
</div>

app/views/job_invocations/_description_fields.html.erb
<%= textarea_f(f, :description, :label => _('Description'), :readonly => 'true', :disabled => disabled, :class => 'description', :rows => 2, :help_inline => description_checkbox_f(f, job_template, disabled)) %>
<div class="description_format_container <%= 'hidden' if f.object.description_format.nil? %>">
  <%= description_format_textarea_f(f, job_template, disabled) %>
</div>

app/views/job_invocations/_form.html.erb
<%= form_for @composer.job_invocation, :html => {'data-refresh-url' => refresh_job_invocations_path, :id => 'job_invocation_form'} do |f| %>

  <% unless @composer.rerun_possible? %>
  <%= alert :text => _('Could not rerun job %{id} because its template could not be found') % { :id => @composer.reruns },
            :class => 'alert alert-block alert-danger has-error',
            :close => false %>
  <% end %>

  <%= selectable_f f, :job_category, @composer.available_job_categories,
                   { :selected => @composer.job_invocation.job_category, :include_blank => @composer.job_invocation.job_category.nil? },
                   :label => _('Job category') %>
  <%= f.hidden_field(:remote_execution_feature_id, :value => @composer.remote_execution_feature_id) %>

  <% selected_templates_per_provider = {} %>
  <% @composer.displayed_provider_types.each do |provider_type| %>
    <%= f.fields_for 'providers' do |providers_fields| %>
      <%= providers_fields.fields_for provider_type do |provider_type_fields| %>
        <% templates_for_provider = @composer.templates_for_provider(provider_type) %>
        <% selected_templates_per_provider[provider_type] = @composer.preselected_template_for_provider(provider_type) || @composer.resolve_job_template(templates_for_provider) %>

        <%= selectable_f provider_type_fields, 'job_template_id', templates_for_provider.map { |t| [t.name, t.id] },
                         { :selected => selected_templates_per_provider[provider_type].try(:id) },
                         { :class => 'job_template_selector', :label => _('Job template'),
                           :data => { :provider_type => provider_type }, :required => true, :onchange => "template_change(this);" }%>
      <% end %>
    <% end %>
  <% end %>

  <%= fields_for @composer.targeting do |targeting_fields| %>
    <span id="bookmark_query_map">
      <% @composer.available_bookmarks.each do |bookmark| %>
        <span id="bookmark-<%= bookmark.id %>" data-query="<%= bookmark.query %>"></span>
      <% end %>
    </span>
    <%= selectable_f targeting_fields, :bookmark_id, @composer.available_bookmarks.map { |b| [b.name, b.id] }, :selected => @composer.targeting.bookmark_id, :include_blank => true %>
    <%= autocomplete_f targeting_fields, :search_query, :search_query => @composer.displayed_search_query, :full_path => auto_complete_search_hosts_path %>

    <div class="form-group ">
      <label class="col-md-2 control-label"><%= _('Resolves to') %></label>

      <div class="col-md-4">
        <%= @composer.targeted_hosts_count %> <%= _('hosts') %>
        <%= button_tag(:type => 'button', :class => 'btn btn-default btn-sm', :title => _("Refresh"), :id => 'refresh_execution_form') do %>
          <%= icon_text('refresh', '', :kind => 'fa') %>
        <% end %>
        <%= button_tag(:type => 'button', :class => 'btn btn-default btn-sm', :title => _("Preview"), :id => 'preview_hosts') do %>
          <%= icon_text('eye', '', :kind => 'fa') %>
        <% end %>
      </div>
    </div>

    <% @composer.displayed_provider_types.each do |provider_type| %>
      <fieldset id="provider_<%= provider_type %>" class="provider_form">
        <%= f.fields_for 'providers' do |providers_fields| %>
          <%= providers_fields.fields_for provider_type do |provider_type_fields| %>
            <%= provider_type_fields.fields_for :job_templates do |job_templates_fields| %>
              <% @composer.templates_for_provider(provider_type).each do |job_template| %>
                <fieldset id="job_template_<%= job_template.id %>" class="job_template_form <%= 'hidden' if job_template != selected_templates_per_provider[provider_type] %>">
                  <%= job_templates_fields.fields_for job_template.id.to_s do |job_template_fields| %>

                    <%= job_template_fields.fields_for :input_values do |input_values_fields| %>
                      <% inputs = job_template.template_inputs_with_foreign.select { |input| input.input_type == 'user' } %>
                      <% inputs.select { |i| i.basic? }.each do |input| %>
                        <%= render :partial => 'template_inputs/invocation_form', :locals => { :input_values_fields => input_values_fields, :composer => @composer, :job_template => job_template, :input => input, :onchange => "regenerate_description(this);" } %>
                      <% end %>

                      <%= advanced_switch_f _('Display advanced fields'), _('Hide advanced fields') %>

                      <div class="advanced hidden">
                        <% inputs.select { |i| i.advanced? }.each do |input| %>
                          <%= render :partial => 'template_inputs/invocation_form', :locals => { :input_values_fields => input_values_fields, :composer => @composer, :job_template => job_template, :input => input } %>
                        <% end %>
                      </div>
                    <% end %>

                    <div class="advanced hidden">
                      <%= job_template_fields.fields_for :provider_input_values do |provider_input_fields| %>
                        <% job_template.provider.provider_inputs.each do |input| %>
                            <%= provider_input_fields.fields_for input.name, input do |input_fields| %>
                              <%= template_input_f(input_fields) %>
                            <% end %>
                        <% end %>
                      <% end %>

                      <%= text_f f, :ssh_user, :value => f.object.ssh_user, :label => _('SSH user'), :label_help => N_('A user to be used for SSH.') %>

                      <% if job_template.effective_user.overridable? %>
                        <%= text_f job_template_fields, :effective_user, :value => @composer.template_invocation(job_template).try(:effective_user), :label => _('Effective user'), :label_help => N_("A user to be used for executing the script. If it differs from the SSH user, su or sudo is used to switch the accounts.") %>
                      <% end %>
                      <%= render :partial => 'description_fields', :locals => { :f => f, :job_template => job_template, :disabled => job_template != selected_templates_per_provider[provider_type] } %>
                    </div>

                    <div class="advanced hidden">
                      <%= number_f job_template_fields, :execution_timeout_interval, :value => f.object.execution_timeout_interval || job_template.execution_timeout_interval, :label => _('Timeout to kill'), :label_help => N_('Time in seconds from the start on the remote host after which the job should be killed.') %>
                    </div>
                  <% end %>
                </fieldset>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </fieldset>
    <% end %>

    <div class="advanced hidden">
      <%= number_f f, :time_to_pickup, :value => f.object.time_to_pickup, :label => _('Time to pickup'), :label_help => N_('Interval in seconds, if the job is not picked up by a client within this interval it will be cancelled.') %>
    </div>

    <div class="advanced hidden">
      <%= password_f f, :password, :placeholder => '*****', :label => _('Password'), :label_help => N_('Password is stored encrypted in DB until the job finishes. For future or recurring executions, it is removed after the last execution.') %>
      <%= password_f f, :key_passphrase, :placeholder => '*****', :label => _('Private key passphrase'), :label_help => N_('Key passhprase is only applicable for SSH provider. Other providers ignore this field. <br> Passphrase is stored encrypted in DB until the job finishes. For future or recurring executions, it is removed after the last execution.') %>
      <%= password_f f, :effective_user_password, :placeholder => '*****', :label => _('Effective user password'), :label_help => N_('Effective user password is only applicable for SSH provider. Other providers ignore this field. <br> Password is stored encrypted in DB until the job finishes. For future or recurring executions, it is removed after the last execution.') %>
    </div>

    <div class="advanced hidden">
      <%= number_f f, :concurrency_level, :label => _('Concurrency level'), :placeholder => 'N', :min => 1, :label_help => N_("Run at most N tasks at a time. If this is set and proxy batch triggering is enabled, then tasks are triggered on the smart proxy in batches of size 1.") %>
    </div>

    <div class="form-group advanced hidden">
      <%= add_label({ :label => _('Execution ordering'), :label_help => _("Execution ordering determines whether the jobs should be executed on hosts in alphabetical order or in randomized order.<br><ul><li><b>Ordered</b> - Executes the jobs on hosts in alphabetical order</li><li><b>Randomized</b> - Randomizes the order in which jobs are executed on hosts</li></ul>") }, f, :randomized_ordering) %>

      <div class="col-md-4">
        <%= radio_button_f targeting_fields, :randomized_ordering, :value => false, :text => _(Targeting::ORDERINGS[Targeting::ORDERED]), :checked => !@composer.targeting.randomized_ordering %>
        <%= radio_button_f targeting_fields, :randomized_ordering, :value => true, :text => _(Targeting::ORDERINGS[Targeting::RANDOMIZED]) %>
      </div>
    </div>

    <div class="form-group">
      <%= add_label({ :label => _('Type of query'), :label_help => _("Type determines when the query is evaluated to hosts.<br><ul><li><b>Static</b> - Executes the job on the current list of target hosts.</li><li><b>Dynamic</b> - Evaluates the list of target hosts just before the job is executed. If you used a filter to select the target hosts, the list of target hosts might be different from the current list.</li></ul>") }, f, :targetting_type) %>

      <div class="col-md-4">
        <%= radio_button_f targeting_fields, :targeting_type, :value => Targeting::STATIC_TYPE, :text => _(Targeting::TYPES[Targeting::STATIC_TYPE]) %>
        <%= radio_button_f targeting_fields, :targeting_type, :value => Targeting::DYNAMIC_TYPE, :text => _(Targeting::TYPES[Targeting::DYNAMIC_TYPE]) %>
      </div>
    </div>
  <% end %>

  <%= trigger_selector f, @composer.triggering %>

  <%= render :partial => 'preview_hosts_modal' %>

  <%= render partial: 'rerun_taxonomies' if action_name == 'rerun' %>
  <%= submit_or_cancel f, false, :cancel_path => job_invocations_path, :disabled => !@composer.rerun_possible? %>
<% end %>

app/views/job_invocations/_preview_hosts_list.html.erb
<% if @dynamic -%>
<div class="alert alert-info alert-dismissable">
    <p><%= _("The final host list may change because the selected query is dynamic.  It will be rerun during execution.") %></p>
</div>
<% end -%>

<% if @hosts.any? -%>
  <ul>
    <% @hosts.each do |host| -%>
        <li><%= link_to h(host), current_host_details_path(host), :target => '_blank' %></li>
    <% end -%>

    <% if @additional > 0 -%>
        <li><%= link_to(n_('...and %{count} more', '...and %{count} more', @additional) % {:count => @additional}, hosts_path(:search => @query, :page => 2), :target => '_blank') %></li>
    <% end -%>
  </ul>
<% else -%>
  <h3><%= _("No hosts found.") %></h3>
<% end -%>

app/views/job_invocations/_preview_hosts_modal.html.erb
<% stylesheet 'foreman_remote_execution/foreman_remote_execution' %>

<!-- modal window -->
<div class="modal fade" id="previewHostsModal" role="dialog" aria-hidden="true" data-url="<%= preview_hosts_job_invocations_path %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" onclick="close_preview_hosts_modal(); return false;"><span aria-hidden="true">&times;</span><span class="sr-only"><%= _('Close') %></span></button>
        <h4 class="modal-title">Preview Hosts</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/job_invocations/_tab_hosts.html.erb
<% if job_invocation.resolved? %>
  <%= react_component('TargetingHosts' ) %>
<% else %>
  <div class="alert alert-warning">
    <%=
        _("The dynamic query '%{query}' was not resolved yet. The list of hosts to which it would resolve now can be seen %{here}." %
            { :query => job_invocation.targeting.search_query,
              :here => link_to(_('here'), hosts_url(:search => job_invocation.targeting.search_query))})
     %>
  </div>
<% end %>

app/views/job_invocations/_tab_overview.html.erb
<% template_invocations = job_invocation.pattern_template_invocations %>
<div class='row'>
  <div class="col-xs-6 col-sm-6 col-md-6">
    <%= render :partial => 'card_results', :locals => { :job_invocation => job_invocation } %>
    <%= render :partial => 'card_schedule', :locals => { :job_invocation => job_invocation } %>
  </div>
  <div class='col-xs-12 col-sm-6 col-md-6'>
  <%= render :partial => 'card_target_hosts', :locals => { :job_invocation => job_invocation } %>
  <% template_invocations.each do |template_invocation| %>
    <%= minicard('user', template_invocation.effective_user || Setting[:remote_execution_effective_user],
                 template_invocation.template.name + ' ' + _('effective user')) %>
    <div class="row">
      <% missing = job_invocation.missing_hosts_count %>
      <% size = missing.zero? ? 12 : 6 %>
      <div class="col-xs-12 col-sm-<%= size %> col-md-<%= size %>" >
        <%= minicard('cluster', job_invocation.total_hosts_count, _('Total hosts')) %>
      </div>
      <% unless missing.zero? %>
      <div class="col-xs-12 col-sm-6 col-md-6" >
          <%= minicard('warning-triangle-o', missing, _('Hosts gone missing'),
                       :tooltip => _('This can happen if the host is removed or moved to another organization or location after the job was started')) %>
      </div>
    <% end %>
    </div>
    <% if template_invocation.input_values.present? %>
      <%= render :partial => 'card_user_input', :locals => { :template_invocation => template_invocation } %>
    <% end %>
  <% end %>
  </div>
</div>
<hr/>
<% if job_invocation.resolved? %>
  <div id="hosts" data-refresh_required="<%= job_invocation.resolved? ? '' : 'true' %>">
    <%= render :partial => 'tab_hosts', :locals => { :job_invocation => job_invocation, :hosts => hosts } %>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= _("The dynamic query '#{job_invocation.targeting.search_query}' was not resolved yet. The list of hosts to which it would resolve now can be seen") %>
    <%= link_to('here.', hosts_url(:search => job_invocation.targeting.search_query)) %>
  </div>
<% end %>