config/routes.rb
Rails.application.routes.draw do
  resources :job_templates, :except => [:show] do
    member do
      get 'clone_template'
      get 'lock'
      get 'export'
      get 'unlock'
      post 'preview'
    end
    collection do
      post 'preview'
      post 'import'
      get 'revision'
      get 'auto_complete_search'
      get 'auto_complete_job_category'
    end
  end

  match 'job_invocations/new', to: 'react#index', :via => [:get], as: 'new_job_invocation'
  match 'job_invocations/new', to: 'job_invocations#create', via: [:post], as: 'create_job_invocation'
  match 'job_invocations/', to: 'job_invocations#legacy_create', via: [:post], as: 'legacy_create_job_invocation'
  match 'job_invocations/:id/rerun', to: 'react#index', :via => [:get], as: 'rerun_job_invocation'
  match 'old/job_invocations/new', to: 'job_invocations#new', via: [:get], as: 'form_new_job_invocation'
  match 'old/job_invocations/:id/rerun', to: 'job_invocations#rerun', via: [:get, :post], as: 'form_rerun_job_invocation'
  get 'legacy/job_invocations/:id', to: 'job_invocations#show', as: 'legacy_job_invocation'
  match 'job_invocations_detail/:id/host_invocation/:host_id', to: 'react#index', :via => [:get], as: 'new_job_invocation_detail_by_host'
  get 'show_template_invocation_by_host/:host_id/job_invocation/:id', to: 'template_invocations#show_template_invocation_by_host'

  resources :job_invocations, :only => [:create, :index] do
    collection do
      get 'preview_job_invocations_per_host'
      post 'refresh'
      get 'chart'
      get 'preview_hosts'
      get 'auto_complete_search'
    end
    member do
      get 'hosts', to: 'job_invocations#list_jobs_hosts'
      post 'cancel'
    end
  end

  get 'job_invocations/:id', to: 'react#index', as: 'job_invocation'

  resources :remote_execution_features, :only => [:show, :index, :update]

  # index is needed so the auto_complete_search can be constructed, otherwise autocompletion in filter does not work
  resources :template_invocations, :only => [:show, :index] do
    collection do
      get 'auto_complete_search'
    end
  end

  constraints(:id => %r{[^/]+}) do
    get 'cockpit/host_ssh_params/:id', to: 'cockpit#host_ssh_params'
  end
  get 'cockpit/redirect', to: 'cockpit#redirect'
  get 'ui_job_wizard/categories', to: 'ui_job_wizard#categories'
  get 'ui_job_wizard/template/:id', to: 'ui_job_wizard#template'
  get 'ui_job_wizard/resources', to: 'ui_job_wizard#resources'
  get 'ui_job_wizard/job_invocation', to: 'ui_job_wizard#job_invocation'

  namespace :api, :defaults => {:format => 'json'} do
    scope '(:apiv)', :module => :v2, :defaults => {:apiv => 'v2'}, :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      resources :job_invocations, :except => [:new, :edit, :update, :destroy] do
        resources :hosts, :only => :none do
          get '/', :to => 'job_invocations#output'
          get '/raw', :to => 'job_invocations#raw_output'
        end
        member do
          get 'hosts'
          post 'cancel'
          post 'rerun'
          get  'template_invocations', :to => 'template_invocations#template_invocations'
          get 'outputs'
          post 'outputs'
        end
      end

      resources :job_templates, :except => [:new, :edit] do
        resources :locations, :only => [:index, :show]
        resources :organizations, :only => [:index, :show]
        get :export, :on => :member
        post :clone, :on => :member
        collection do
          get 'revision'
          post 'import'
        end
      end

      resources :organizations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :locations, :only => [:index] do
        resources :job_templates, :only => [:index, :show]
      end

      resources :templates, :only => :none do
        resources :foreign_input_sets, :only => [:index, :show, :create, :destroy, :update]
      end

      get 'hosts/:id/available_remote_execution_features', to: 'remote_execution_features#available_remote_execution_features'

      resources :remote_execution_features, :only => [:show, :index, :update]
    end
  end
end

app/controllers/api/v2/job_templates_controller.rb
module Api
  module V2
    class JobTemplatesController < ::Api::V2::BaseController
      include ::Api::Version2
      include ::Foreman::Renderer
      include ::Foreman::Controller::ProvisioningTemplates
      include ::Foreman::Controller::Parameters::JobTemplate

      before_action :find_optional_nested_object
      before_action :find_resource, :only => %w{show update destroy clone export}

      before_action :handle_template_upload, :only => [:create, :update]

      wrap_parameters JobTemplate, :include => (JobTemplate.attribute_names + [:ssh])

      api :GET, '/job_templates/', N_('List job templates')
      api :GET, '/locations/:location_id/job_templates/', N_('List job templates per location')
      api :GET, '/organizations/:organization_id/job_templates/', N_('List job templates per organization')
      param_group :taxonomy_scope, ::Api::V2::BaseController
      param_group :search_and_pagination, ::Api::V2::BaseController
      def index
        @job_templates = resource_scope_for_index
      end

      api :POST, '/job_templates/import', N_('Import a job template from ERB')
      param_group :template_import_options, ::Api::V2::BaseController
      param :template, String, :required => true, :desc => N_('Template ERB')
      param :overwrite, :bool, :required => false, :desc => N_('Overwrite template if it already exists')
      def import
        options = params[:overwrite] ? { :update => true } : { :build_new => true }
        # the Template superclass expects hash indexed by symbols
        options = options.merge(params.permit(:options => {}).try(:[], :options).try(:to_h) || {}).with_indifferent_access

        @job_template = JobTemplate.import_raw(params[:template], options)
        @job_template ||= JobTemplate.new
        process_response @job_template.save
      end

      api :GET, '/job_templates/:id/export', N_('Export a job template to ERB')
      param :id, :identifier, :required => true
      def export
        Foreman::Deprecation.api_deprecation_warning('Exporting template is provided by Foreman core, please use that endpoint instead')
        send_data @job_template.to_erb, :type => 'text/plain', :disposition => 'attachment', :filename => @job_template.filename
      end

      api :GET, '/job_templates/:id', N_('Show job template details')
      param :id, :identifier, :required => true
      def show
      end

      def_param_group :job_template do
        param :job_template, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true, :desc => N_('Template name')
          param :description, String
          param :job_category, String, :required => true, :desc => N_('Job category')
          param :description_format, String, :required => false, :desc => N_('This template is used to generate the description. ' +
                                                                             'Input values can be used using the syntax %{package}. ' +
                                                                             'You may also include the job category and template ' +
                                                                             'name using %{job_category} and %{template_name}.')
          param :template, String, :required => true
          param :provider_type, RemoteExecutionProvider.provider_names, :required => true, :desc => N_('Provider type')
          param :snippet, :bool, :allow_nil => true
          param :audit_comment, String, :allow_nil => true
          param :locked, :bool, :desc => N_('Whether or not the template is locked for editing')
          param :effective_user_attributes, Hash, :desc => N_('Effective user options') do
            param :value, String, :desc => N_('What user should be used to run the script (using sudo-like mechanisms)'), :allowed_nil => true
            param :overridable, :bool, :desc => N_('Whether it should be allowed to override the effective user from the invocation form.')
            param :current_user, :bool, :desc => N_('Whether the current user login should be used as the effective user')
          end
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, '/job_templates/', N_('Create a job template')
      param_group :job_template, :as => :create
      def create
        @job_template = JobTemplate.new(job_template_params)
        process_response @job_template.save
      end

      api :PUT, '/job_templates/:id', N_('Update a job template')
      param :id, :identifier, :required => true
      param_group :job_template
      def update
        process_response @job_template.update(job_template_params)
      end

      api :GET, '/job_templates/revision'
      param :version, String, :desc => N_('Template version')
      def revision
        audit = Audit.authorized(:view_audit_logs).find(params[:version])
        render :json => audit.revision.template
      end

      api :DELETE, '/job_templates/:id', N_('Delete a job template')
      param :id, :identifier, :required => true
      def destroy
        process_response @job_template.destroy
      end

      def_param_group :job_template_clone do
        param :job_template, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true, :desc => N_('Template name')
        end
      end

      api :POST, '/job_templates/:id/clone', N_('Clone a provision template')
      param :id, :identifier, :required => true
      param_group :job_template_clone, :as => :create
      def clone
        original = @job_template
        @job_template = @job_template.clone
        @job_template.cloned_from = original
        @job_template.name = job_template_params[:name]
        process_response @job_template.save
      end

      def resource_name(nested_resource = nil)
        nested_resource || 'job_template'
      end

      private

      def job_template_params
        job_template_params = params[:job_template]
        effective_user_attributes = (job_template_params.delete(:ssh) || {}).fetch(:effective_user, {})
        job_template_params.merge(:effective_user_attributes => effective_user_attributes)
        super
      end

      def action_permission
        case params[:action]
        when 'clone'
          :create
        when 'import'
          :create
        when 'export'
          :view
        else
          super
        end
      end

      def resource_class
        JobTemplate
      end

      def allowed_nested_id
        %w(location_id organization_id)
      end
    end
  end
end

app/controllers/concerns/foreman/controller/parameters/job_template.rb
module Foreman::Controller::Parameters::JobTemplate
  extend ActiveSupport::Concern
  include Foreman::Controller::Parameters::Taxonomix
  include Foreman::Controller::Parameters::Template
  include Foreman::Controller::Parameters::TemplateInput
  include Foreman::Controller::Parameters::ForeignInputSet

  class_methods do
    def job_template_effective_user_filter
      Foreman::ParameterFilter.new(::JobTemplateEffectiveUser).tap do |filter|
        filter.permit_by_context(:value, :current_user, :overridable,
          :nested => true)
      end
    end

    def job_template_params_filter
      Foreman::ParameterFilter.new(::TemplateInput).tap do |filter|
        filter.permit :job_category, :provider_type, :description_format, :execution_timeout_interval, :output_template_ids => [],
          :effective_user_attributes => [job_template_effective_user_filter],
          :template_inputs_attributes => [template_input_params_filter],
          :foreign_input_sets_attributes => [foreign_input_set_params_filter]
        add_template_params_filter(filter)
        add_taxonomix_params_filter(filter)
      end
    end
  end

  def job_template_params
    self.class.job_template_params_filter.filter_params(params, parameter_filter_context, :job_template)
  end
end

app/controllers/job_templates_controller.rb
class JobTemplatesController < ::TemplatesController
  include ::Foreman::Controller::Parameters::JobTemplate

  def load_vars_from_template
    return unless @template

    @locations        = @template.locations
    @organizations    = @template.organizations
  end

  def auto_complete_job_category
    @job_categories = resource_base.where(['job_category LIKE ?', "%#{params[:search]}%"]).pluck(:job_category).uniq
    render :json => @job_categories.map { |name| { 'completed' => '', 'part' => name, 'label' => name, 'category' => '' } }.to_json
  end

  def preview
    find_resource if @template.blank?
    base = Host.authorized(:view_hosts, Host)
    host = params[:preview_host_id].present? ? base.find(params[:preview_host_id]) : base.first
    @template.template = params[:template]
    renderer = InputTemplateRenderer.new(@template, host)
    output = renderer.preview
    if output
      render :plain => output
    else
      render status: :not_acceptable,
        plain: _(
          'Problem with previewing the template: %{error}. Note that you must save template input changes before you try to preview it.' %
          {:error => renderer.error_message}
        )
    end
  end

  def import
    contents = params.fetch(:imported_template, {}).fetch(:template, nil).try(:read)

    @template = JobTemplate.import_raw(contents, :update => ActiveRecord::Type::Boolean.new.deserialize(params[:imported_template][:overwrite]))
    if @template&.save
      flash[:success] = _('Job template imported successfully.')
      redirect_to job_templates_path(:search => "name = \"#{@template.name}\"")
    else
      @template ||= JobTemplate.import_raw(contents, :build_new => true)
      @template.valid?
      flash[:warning] = _('Unable to save template. Correct highlighted errors')
      render :action => 'new'
    end
  end

  private

  def find_resource
    if params[:id]
      super
    else
      @template = resource_class.new(params[type_name_plural])
    end
  end

  def action_permission
    case params[:action]
      when 'auto_complete_job_category', 'export'
        :view_job_templates
      else
        super
    end
  end
end

app/views/job_templates/_custom_tab_headers.html.erb
<li><a href="#template_job" data-toggle="tab"><%= _("Job") %></a></li>
<li><a href="#template_type" data-toggle="tab"><%= _("Type") %></a></li>
<li><a href="#output_templates" data-toggle="tab"><%= _('Output Templates') %></a></li>

app/views/job_templates/_custom_tabs.html.erb
<div class="tab-pane" id="template_job">

  <%= autocomplete_f(f, :job_category,
        :search_query => @template.job_category,
        :placeholder => _("Job category") + ' ...',
        :disabled => @template.locked?) %>
  <%= text_f f, :description_format,
             :disabled => @template.locked?,
             :label_help => description_format_help %>

  <%= select_f f, :provider_type, providers_options, :first, :last, :disabled => @template.locked? %>

  <%= number_f f, :execution_timeout_interval, :disabled => @template.locked?, :label => _('Timeout to kill') %>

  <div class="children_fields">
    <%= new_child_fields_template(f, :foreign_input_sets, { :partial => "template_inputs/foreign_input_set_form" }) %>
    <%= f.fields_for :foreign_input_sets do |ff| %>
      <div class="template_input_form fields">
        <%= render 'template_inputs/foreign_input_set_form', :f => ff %>
      </div>
    <% end %>
    <%= add_child_link '+ ' + _("Add Foreign Input Set"), :foreign_input_sets, { :title => _('add an input set for this template to reference a different template inputs') } unless @template.locked? %>
  </div>

  <div class="children_fields">
    <%= field_set_tag _("Effective user") do %>
      <%= f.fields_for :effective_user, @template.effective_user do |ff| %>
        <div class="effective_user_form fields">
          <%= text_f ff, :value, :disabled => @template.locked? %>
          <%= checkbox_f ff, :current_user, :disabled => @template.locked? %>
          <%= checkbox_f ff, :overridable, :disabled => @template.locked? %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

<div class="tab-pane" id="template_type">
  <%= checkbox_f f, :snippet, :onchange => "snippet_changed(this)", :label=>_('Snippet'), :disabled => @template.locked? %>
</div>

app/views/job_templates/_import_job_template_modal.html.erb
<% stylesheet 'foreman_remote_execution/foreman_remote_execution' %>

<!-- modal window -->
<div class="modal fade" id="importJobTemplateModal" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" onclick="close_import_job_template_modal(); return false;"><span aria-hidden="true">&times;</span><span class="sr-only"><%= _('Close') %></span></button>
        <h4 class="modal-title">Import Job Template</h4>
      </div>
      <div class="modal-body">
        <%= form_for :imported_template, :url => import_job_templates_path do |f| %>
          <%= file_field_f f, :template, :size => "col-md-10", :help_block  => _("Select an ERB file to upload in order to import a job template.  The template must contain metadata in the first ERB comment.") %>
          <%= checkbox_f(f, :overwrite, :label => _('Overwrite'), :help_block => _("Whether to overwrite the template if it already exists")) %>
          <%= submit_or_cancel f, false, :cancel_path => 'javascript:close_import_job_template_modal();' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/job_templates/edit.html.erb
<%= javascript 'foreman_remote_execution/template_input' %>

<%= breadcrumbs(
    items: [
      {
        caption: _('Job Templates'),
        url: url_for(job_templates_path)
      },
      {
        caption: _('Edit %s' % @template.to_label)
      }
    ]
  )
%>

<% title _("Edit Job Template") %>

<%= render :partial => 'form' %>

app/views/job_templates/index.html.erb
<%= javascript 'foreman_remote_execution/job_templates' %>
<%= javascript 'foreman_remote_execution/template_input' %>

<% title _("Job Templates") %>
<% title_actions(documentation_button('Managing_Hosts', type: 'docs', chapter: 'creating-a-job-template_managing-hosts'),
                 link_to_function(_('Import'), 'show_import_job_template_modal();', :class => 'btn btn-default'),
                 new_link(_("New Job Template"))) %>

<table class="<%= table_css_classes('table-fixed') %>">
  <thead>
    <tr>
      <th class="col-md-6"><%= sort :name, :as => s_("JobTemplate|Name") %></th>
      <th class="col-md-1"><%= sort :snippet, :as => s_("JobTemplate|Snippet") %></th>
      <th class="col-md-1"><%= sort :locked, :as => s_("JobTemplate|Locked"), :default => "DESC" %></th>
      <th class="col-md-1"><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% for job_template in @templates %>
      <tr>
        <td class="display-two-pane ellipsis"><%= link_to_if_authorized job_template,
                                                               hash_for_edit_job_template_path(:id => job_template).merge(:auth_object => job_template, :authorizer => authorizer) %></td>
        <td align='center'><%= checked_icon job_template.snippet %></td>
        <td align='center'>
          <%= locked_icon job_template.locked?, _("This template is locked for editing.") %>
        </td>
        <td>
          <%= action_buttons(*permitted_actions(job_template)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate_with_info @templates %>

<%= render :partial => 'import_job_template_modal' %>

app/views/job_templates/new.html.erb
<%= javascript 'foreman_remote_execution/template_input' %>

<% title _("New Job Template") %>

<%= render :partial => 'form' %>